# Generated by Django 3.1.7 on 2021-11-14 14:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import paneluser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_pay', 'در انتظار پرداخت'), ('doing', 'درحال انجام'), ('cancel', 'لغو شده'), ('edit', 'درحال ویرایش'), ('success', 'انجام شده')], max_length=256, null=True, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=paneluser.models.order_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='packs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('enable_check', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('full_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depertment', models.CharField(choices=[('finance', 'فروش و مالی'), ('technical', 'فنی'), ('moderator', 'مدیریت')], max_length=256, null=True, verbose_name='دپارتمان')),
                ('priority', models.CharField(choices=[('very_important', 'خیلی'), ('important', 'مهم'), ('simple', 'عادی')], max_length=256, null=True, verbose_name='میزان اهمیت')),
                ('status', models.CharField(choices=[('created', 'دریافت شده'), ('customer_answer', 'پاسخ مشتری'), ('admin_answer', 'پاسخ فروشنده'), ('doing', 'در دست پیگیری'), ('closed', 'بسته شده')], max_length=256, null=True, verbose_name='وضعیت')),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=paneluser.models.ticket_file_path)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticketpm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=paneluser.models.ticket_file_path)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('amount', models.CharField(blank=True, max_length=256, null=True)),
                ('refnum', models.CharField(blank=True, max_length=256, null=True)),
                ('irtoken', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=256, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=256, null=True)),
                ('verify_check', models.BooleanField(default=False, verbose_name='Purchase okay?')),
                ('final_code', models.CharField(blank=True, max_length=256, null=True)),
                ('packs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.packs')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='packs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.packs'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
