# Generated by Django 3.1.7 on 2021-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/'),
        ),
    ]
