# Generated by Django 3.2.7 on 2021-11-20 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0004_auto_20211120_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packs',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
