# Generated by Django 3.2.7 on 2021-11-20 08:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paneluser.models


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0005_auto_20211120_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=paneluser.models.order_file_path, verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='packs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.packs', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='enable_check',
            field=models.BooleanField(default=False, verbose_name='محصول برای فروش فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='full_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=paneluser.models.ticket_file_path, verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.orders', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=paneluser.models.ticket_file_path, verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paneluser.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن همراه'),
        ),
    ]
