# Generated by Django 3.2.7 on 2021-11-20 10:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0008_alter_orders_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='full_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='packs',
            name='short_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
