# Generated by Django 3.2.7 on 2021-11-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0009_auto_20211120_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpm',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paneluser.ticket', verbose_name='تیکت'),
        ),
    ]
