# Generated by Django 3.2.7 on 2021-11-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0010_alter_ticketpm_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
