# Generated by Django 3.2.7 on 2021-11-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0011_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpm',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketpm',
            name='ticketid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paneluser.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketpm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
